symbols: ["BTC/USDT", "ETH/USDT"]
timeframe: "1h"   # options: 1m,3m,5m,15m,30m,1h,4h,1d
start_days: 180    # how many days back to fetch
rate_limit_ms: 200 # sleep between OHLCV batches

fees_bps: 10       # 0.10% taker per side
slippage_bps: 2    # 0.02% per trade (simple model)
init_cash: 8000

strategies:
  ema_cross:
    fast_windows: [10, 20, 30]
    slow_windows: [40, 60, 80]
    sl_stop_pct: 0.02   # 2%
    tp_stop_pct: 0.04   # 4%
  bb_meanrev:
    window_list: [20, 30]
    k_list: [2.0, 2.5]
    sl_stop_pct: 0.015
    tp_stop_pct: 0.02
